language: ruby
sudo: false
cache: bundler
rvm:
- 2.2.4
before_script:
  #- bundle exec rake build
  - bundle exec sass --update -r sass-globbing  assets/sass:assets/css
  - bundle exec jekyll build
after_success:
- "./_scripts/travis_deploy.sh"
branches:
  only:
  - master
  - live
env:
  global:
  - secure: P1ORydEGBb+O3kRj220/VYlR5mY/Tc+Jggv7lsP+tgbIHb/kbWOEzinlwmURyYBwtZNP7tt220N5cJjBUbVNiRjWDP86iGsEzmWWZpNe5/9zMevkPDrKtRe37mW0uP9gClfoZxFdPw2KFIolm4DINZtMQe8N5Lhxa+AfXSrRkSa2Fr1b2aFaeEzjNkq9ohPi3zyJVgjTFDy8fv9UQmeUl2C2uRa0npAoAqqy/mzXUjAtHRO+RRC2ETX4+eE8VP0olI5xH7tEGRgV0hmv8Ya5BcrXMqnk1+iDkL5EmEqedhGKtfU8G5dYIkGbTDaORcsmI+LcbX4RJxnr+sYWl4b+WYvgvGB7NEDtFxPB/D6jgBNqboTPt3oxemSCHLV1srZhIWAftlEcX6AZWvxC4OI+ojMxV7srwN9gHpnST0+SlUPfK2mCqKwRabjRwO/42K1thBVjMfrODBJztQ3Am6T6zOznZ1yWjqmn/jvAE70fPZ6eCdF4rl76+wEQ421juXwKyVQzEEEuv2FI+6ibIVLt/D2RcFHLgNgchetgXl4UGkJw5ep8rMz27hqgMtxnDema1mCYfIf+PoYW3N6NhHTEiHdTuNiFPYSiWiDeuqqxr/AjRf0R8NxySaxaCrerWxv44WO5qOZPjlB3Dg5rx+jBr6Ercyw3pqI/D9nVNt7GUmk=
  - secure: EHlvhcRvvYM3DTr8KsSo6I/MQwvgrZ16+CTHpJuHg4uG/wBWNllwRhwqZEnixD1cQ1hhSD2FrvaS+TXr/6RK5FQJFGcT/m7q7pBxPCJ1o/WwaF/xJLc2owRib/auEoucRHmH1Aor7iLb719x+GY2eHmsjJFx/Vi0278k35gtwEGVDIKFEkNbl+18hbgTRofytSfbIdlw+CqpFHv1781qGhZntPTKnMZHYNkB9H7sMT9PM5SI1XFXl+2pVCm7qHbm7HGIpLZ0De4h1HHbzWXBqgdRb4cp2M1wQ+ajkkQyYy9/sGdg3WCG5Bzca15nCQCf7QMAhWbF2mJ15UO6cF/GZS1Lg6hi33jeEwKTBLcODNC1SD9N2IRwMxonKxsZI0YQ+FFUU1Udg28RmI56wl97RRL3qgvxAWuua8+3InXVBELqEiGanQMC7lHItfyibUbIHcrmjbVGocQMniPGc+/UE6fZNLzRzJdYFZeKohs/pfr9dIXsM3/+LZpa+k4YfZqgcTTZOeNx69SKint4M1j6ucXZqfOsOSTrKtK2OOL5hn73XLOCq6A9Q3WWI4XGj7U5XksckVeiByCkagZph7OoGi4dSmJiPdPCNrYTVE+K9OwbNg/ugOm42WOHYD/qKRPrZdzjBx5GN0/KHdWl/F5n49b7qqoc6N1CVcJXfNYe3v4=
