language: ruby
# use container-based infrastructure to speed up build
# see http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
# cache bundle to speed up build
# see http://docs.travis-ci.com/user/caching/#Bundler
cache: bundler

rvm:
- 2.2.4

before_script:
- bundle exec sass -r sass-globbing --update assets/sass:assets/css
- bundle exec jekyll build
after_success:
- "./_scripts/travis_deploy.sh"
branches:
  only:
  - master
  - live
