# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Humane Society of the United States
description: A Humane Society Starts with You
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: ['Gemfile', '.gitignore', 'Gemfile.lock', 'Rakefile', 'assets/sass', 'vendor', '.travis.yml', 'Guardfile', 's3_website.yml']
